<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <title>Document</title>
</head>
<body class="container-fluid">

     <h1 class="text-center">Déposer</h1>

     <form action="" method="post">
          <input type="hidden" value="<?= $_GET['ref'] ?>" name="reference">
          <div class="form-group">
               <label for="">Montant à déposer</label>
               <input type="text" name="montant" class="form-control">
          </div>
          <div class="mt-3">
               <input type="submit" name="deposer" value="Déposer">
          </div>
     </form>

</body>
</html>