<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
     <title>Document</title>
</head>
<body class="container-fluid">

     <h1 class="text-center">VirerVers un compte</h1>

     <form action="" method="post">
          <input type="hidden" value="<?= $_GET['ref'] ?>" name="reference">
          <div class="form-group">
               <label for="">Montant à virer</label>
               <input type="text" name="montant" class="form-control">
          </div>
          <label for="">Compte destinataire</label>
          <select name="destination" class="form-select">
               <?php foreach($comptes as $key => $compte): ?>
                    <?php if( $modele->getTitulaire($compte->getTitulaire())->getid() != $compteCourant->getTitulaire() ): ?>
                         <option value="<?= $compte->getTitulaire() ?>"> 
                              <?= $modele->getTitulaire($compte->getTitulaire())->getPrenom() ?>
                         </option>
                    <?php endif; ?>
               <?php endforeach; ?>
          </select>
          <div class="mt-3">
               <input type="submit" name="virer" value="Virer">
          </div>

     </form>

</body>
</html>